services:
  - type: web
    name: mvp-contabot-2-0
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT --log-level debug --workers 1
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: URL_DATALOGIC
        sync: false
      - key: USUARIO_DATALOGIC
        sync: false
      - key: CLAVE_DATALOGIC
        sync: false
      - key: EMPRESA_DATALOGIC
        sync: false
      - key: TRANSACTION_POOLER
        sync: false 