services:
  - type: web
    name: contabot-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: URL_DATALOGIC
        sync: false
      - key: USUARIO_DATALOGIC
        sync: false
      - key: CLAVE_DATALOGIC
        sync: false
      - key: EMPRESA_DATALOGIC
        sync: false
      - key: TRANSACTION_POOLER
        sync: false 